Repository dsfsi/masakhane-web, pull requests merged in 2022-12, with the labels that each got.

#62 Update README on run standalone backend for polyglot error
  README.md
Labels: bug, documentation

#68 Documentation
  README.md
  docs/github_docs/debugging_setup.md
  docs/github_docs/start_app_locally_doc.md
  docs/github_docs/start_app_prod_doc.md
  src/client/Dockerfile
  src/client/package-lock.json
  src/client/package.json
Labels: bug, documentation

#70 🔥 👽️ ✨ (Client/Server): Major updates to system
  src/client/package-lock.json
  src/client/package.json
  src/client/src/components/translateCard.js
  src/client/webpack.config.js
  src/server/core/__init__.py
  src/server/core/model_load.py
  src/server/core/resources/translate.py
  src/server/entrypoint.sh
  src/server/manage.py
  src/server/requirements.txt
Labels: enhancement, dependencies, python, backend

#78 Changing fetch req in translateCard.js
  src/client/src/components/translateCard.js
Labels: bug
